server:
  port: 8081
spring:
  application:
    name: livestream
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livestream?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dut201892487
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 124.70.182.160
    port: 6379
    password: 197604
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  security:
    user:
      name: admin
      password: 123456
mybatis-plus:
  type-aliases-package: com.ydh.livestream.entity # 别名扫描包
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.ydh: debug